### ISSUE TITLE
Makefile/Env setup for Docker and Rinkeby Hubs

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/project-management-pipeline#154]
We need users to be able to easily spin up a version of the Minikube Hub and inject their environment variables without having to deal with docker/helm/kube.

Ideally users can just create a .env at the root and then `make local-hub` or `make rinkeby-hub`.

@bohendo was doing some work on this, let's circle up with him.

**Comment by bohendo** [comment]
A PR from the kernel's autobuild branch will be incoming today. Just have one more thing to set-up to make developer's lives easier.

Disclaimer: this branch sets up a handful of container images and then deploys them using docker swarm, only because that's the orchestrator I'm most familiar with. These container images can be reused in kube pods though so porting them over to minikube shouldn't be too hard.

A .env in the root would be really easy to add too, only question is which env vars need to be added. The dev mode deployment currently comes with database & ganache services wired up & deployed along side the hub/chainsaw so everything works out of the box without needing any input from the user.

A flag for using a local vs rinkeby eth provider would be a useful thing to specify though & shouldn't be too hard to incorporate.

**Comment by ArjunBhuptani** [comment]
Nice! Will review this today with everyone.

**Comment by rhlsthrm** [comment]
We're going to go with the Docker deployment not Kubernetes for this, it's much easier to get a hub up and running.
